version: "3.9"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: "/api"
        NEXT_PRIVATE_API_URL: "http://nginx/api"
    container_name: frontend
    expose:
      - "3000"
    env_file:
      - ./frontend/.env
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: backend
    expose:
      - "4000"
    env_file:
      - ./backend/.env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge