name: Production CI-CD

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

env:
  REGISTRY: docker.io
  BACKEND_IMAGE: muhammadmuhidin/core-backend
  FRONTEND_IMAGE: muhammadmuhidin/core-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: |
          docker build \
            -t $BACKEND_IMAGE:${{ steps.vars.outputs.IMAGE_TAG }} \
            -t $BACKEND_IMAGE:latest \
            ./backend

      - name: Push backend image
        run: |
          docker push $BACKEND_IMAGE:${{ steps.vars.outputs.IMAGE_TAG }}
          docker push $BACKEND_IMAGE:latest

      - name: Build frontend image
        run: |
          docker build \
            -t $FRONTEND_IMAGE:${{ steps.vars.outputs.IMAGE_TAG }} \
            -t $FRONTEND_IMAGE:latest \
            ./frontend

      - name: Push frontend image
        run: |
          docker push $FRONTEND_IMAGE:${{ steps.vars.outputs.IMAGE_TAG }}
          docker push $FRONTEND_IMAGE:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
#            cd /root/repo-folder
#            export IMAGE_TAG=${{ steps.vars.outputs.IMAGE_TAG }}
#            docker compose pull
#            docker compose up -d --remove-orphans
#
